name: MSBuild
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v2
    - name: Build
      run: msbuild /m /p:Configuration=Release JukeBoxPlayer
    - name: Copy MSI
      run: Copy-Item "bin/Release/MynaJukeBox.msi" "MynaJukeBox-win-x86-${{ github.ref_name }}.msi"
    - name: Create github release
      run: gh release create "${{ github.ref_name }}" "MynaJukeBox-win-x86-${{ github.ref_name }}.msi"
